Gene2symbol
snakemake-workflows/rna-seq-star-deseq2 pull request #39
Opened 2021-08-20 07:19 UTC by jafors

This PR adds a script and a rule to add gene symbols to the ensembl ids via biomaRt. This happens after the deseq2 rules since the mapping between ensID and symbol is not always unique and I don't think it's a good idea to work on the more exact ensIDs for the analysis.

Additionally, there are some generalizations and fixes.

2021-08-20 08:43 UTC, johanneskoester requested changes

2021-08-20 08:43 UTC, johanneskoester commented on workflow/scripts/deseq2-init.R
> +# coldata <- coldata[order(row.names(coldata)), , drop=F]
Can you remove the commented out stuff?

2021-08-20 08:44 UTC, jafors commented on workflow/scripts/deseq2-init.R
> +# coldata <- coldata[order(row.names(coldata)), , drop=F]
Sure, I'm still testing sth here. :)

2021-08-24 15:38 UTC, johanneskoester approved these changes

2021-08-24 15:39 UTC, merged