Bugfix
snakemake-workflows/rna-seq-star-deseq2 pull request #41
Opened 2021-09-06 12:07 UTC by kilpert

Fix some bugs

2021-09-09 12:29 UTC, kilpert commented
The fixed workflow runs fine for me. Maybe the test is broken?

2023-01-30 10:13 UTC, dlaehnemann requested changes
@kilpert Many thanks for these fixes. I only saw them now, while wrapping up another PR. Would you be willing to address my suggestions and rebase onto the latest master? Then we could get your fixes in!

2023-01-30 10:13 UTC, dlaehnemann commented on config/config.yaml
> +  star: "--outSAMtype BAM SortedByCoordinate"
This should probably just be empty, with the `SortedByCoordinate` staying in the rule definition's extra (we always want sorted BAMs, right?):
```suggestion
  star: ""
```

2023-01-30 10:13 UTC, dlaehnemann commented on workflow/rules/align.smk
> +        extra="--quantMode GeneCounts --sjdbGTFfile {} {}".format(
Probably leave this in here and only delete the conflicting option in the `config.yaml`:
```suggestion
        extra="--outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --sjdbGTFfile {} {}".format(
```

2023-01-30 10:13 UTC, dlaehnemann commented on workflow/rules/common.smk
> +                        "results/trimmed/{sample}-{unit}_{group}.fastq.gz",
I usually prefer to have only underscores in folder and file names. It avoids confusion. And all ambiguity should be removed by the wildcard_constraints above, right?
```suggestion
                        "results/trimmed/{sample}_{unit}_{group}.fastq.gz",
```

2023-01-30 10:13 UTC, dlaehnemann commented on workflow/rules/common.smk
> +        return {"fq1": "trimmed/{sample}-{unit}_single.fastq.gz".format(**wildcards)}
As above:
```suggestion
        return {"fq1": "trimmed/{sample}_{unit}_single.fastq.gz".format(**wildcards)}
```

2023-01-30 10:13 UTC, dlaehnemann commented on workflow/rules/trim.smk
> +        extra=config["params"]["cutadapt-pe"],
Very important fix, to ensure the `params` from the `config.yaml` are actually picked up!

2023-04-19 15:58 UTC, dlaehnemann commented
Almost all of the suggested changes have been incorporated through the recent pull requests. For example:
#61

The ones that weren't incorporated yet, I have added in PR #66 currently under review (referencing the commits in this PR).

So many thanks for these useful suggestions. I'll close this PR for now, as all of its suggestions have found their way into the code base.

2023-04-19 15:58 UTC, closed without merging